"""Initial schema with reviews, themes, and users

Revision ID: 081b1458be46
Revises: 
Create Date: 2026-06-23 12:35:57.800734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081b1458be46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('theme', sa.String(length=255), nullable=True),
    sa.Column('theme_confidence', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_review_source_external_id')
    )
    op.create_index(op.f('ix_reviews_app_name'), 'reviews', ['app_name'], unique=False)
    op.create_index(op.f('ix_reviews_date'), 'reviews', ['date'], unique=False)
    op.create_index(op.f('ix_reviews_rating'), 'reviews', ['rating'], unique=False)
    op.create_index(op.f('ix_reviews_sentiment'), 'reviews', ['sentiment'], unique=False)
    op.create_index(op.f('ix_reviews_source'), 'reviews', ['source'], unique=False)
    op.create_index('ix_reviews_source_theme', 'reviews', ['source', 'theme'], unique=False)
    op.create_index(op.f('ix_reviews_theme'), 'reviews', ['theme'], unique=False)
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('theme_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('top_reviews', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_theme_name'), 'themes', ['theme_name'], unique=True)
    op.create_index(op.f('ix_themes_topic_id'), 'themes', ['topic_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_themes_topic_id'), table_name='themes')
    op.drop_index(op.f('ix_themes_theme_name'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_reviews_theme'), table_name='reviews')
    op.drop_index('ix_reviews_source_theme', table_name='reviews')
    op.drop_index(op.f('ix_reviews_source'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_sentiment'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_rating'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_date'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_app_name'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
